### ISSUE TITLE
effects of tillage on SOC

### ISSUE THREAD

**Issue by KatharinaRei** [climatefarmers/soil-modelling#19]

**Comment by kss-9** [comment]
can this be reflected by changing decomposition rates of soil compartments? research includes  (on notion) - "Soil C storage as affected by tillage and straw management: An assessment using field measurements and model predictions"

**Comment by Clare2D** [comment]
So I read through the article and there is no relationship presented - or did I miss something? Do we have any other leads on this?

**Comment by kss-9** [comment]
it seems that they are making adjustment to compartment amounts. i don't understand fully yet if they are affecting rates as well.. would be nice to review the "cohort model" with you.
specifically im looking at the model fit to soil analyses section 3.2
'There is no standard way in either model to differentiate between CT and RT treatments. However, we achieved a fit  in the cohort model to the experimental data under RT by reducing the decay rate of the initial SOC. Specifically, 100% of the original SOC in the RT plots had to be put in the protected pool with a decay ? =500 years, compared to 56% of the original SOC for the CT plots. The annual cohorts had the same decay rate for the RT and CT cases (Table 5). This knowledge gained from using the cohort model to understand the decay mechanism of both the input cohorts and the initial SOC enabled the RT case to be modelled using RothC by considering all of the initial SOC to be inert (IOM).

**Comment by Clare2D** [comment]
Solved by implementing the factors suggested in CFT
