### ISSUE TITLE
how to calculate initial carbon pools

### ISSUE THREAD

**Issue by kss-9** [climatefarmers/soil-modelling#20]
how to best estimate initial carbon pool breakdown
currently - run model backwards from 'equilibrium' run, but not sure if this properly reflects agri practices

research suggests we can tie current soil samples and SOC measured to inverse run of model if also can estimate c_inputs data

**Comment by kss-9** [comment]
see paper by Nemo2017_SoilOrganicCarbon Equilibrium and model initialisation methods application to RothC model for potential method

**Comment by Clare2D** [comment]
solved with https://sci-hub.se/https://onlinelibrary.wiley.com/doi/epdf/10.1111/ejss.12036
